{% set version = "2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fma_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fma/fma_{{ version }}.tar.gz
  sha256: 400dea4d2b6e73ed686d901fbab1b4f930dfcdd67fbd0bb3abc34a707656cf78

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-forecast >=8.1
  run:
    - r-base
    - r-forecast >=8.1

test:
  commands:
    - $R -e "library('fma')"           # [not win]
    - "\"%R%\" -e \"library('fma')\""  # [win]

about:
  home: https://pkg.robjhyndman.com/fma/, https://github.com/robjhyndman/fma
  license: GPL-3.0-only
  summary: 'All data sets from "Forecasting: methods and applications" by Makridakis, Wheelwright & Hyndman (Wiley, 3rd ed., 1998) <https://robjhyndman.com/forecasting/>.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: fma
# Title: Data Sets from "Forecasting: Methods and Applications" by Makridakis, Wheelwright & Hyndman (1998)
# Description: All data sets from "Forecasting: methods and applications" by Makridakis, Wheelwright & Hyndman (Wiley, 3rd ed., 1998) <https://robjhyndman.com/forecasting/>.
# Version: 2.4
# Depends: R (>= 2.0.0), forecast (>= 8.1)
# LazyData: yes
# LazyLoad: yes
# Authors@R: c( person("Rob", "Hyndman", email="Rob.Hyndman@monash.edu", role=c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-2140-5352")), person("Justin", "Carmody", role="ctb"))
# License: GPL-3
# URL: https://pkg.robjhyndman.com/fma/, https://github.com/robjhyndman/fma
# BugReports: https://github.com/robjhyndman/fma/issues
# RoxygenNote: 7.0.2
# Suggests: knitr, rmarkdown, tidyverse
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-01-14 00:36:06 UTC; robjhyndman
# Author: Rob Hyndman [aut, cre, cph] (<https://orcid.org/0000-0002-2140-5352>), Justin Carmody [ctb]
# Maintainer: Rob Hyndman <Rob.Hyndman@monash.edu>
# Repository: CRAN
# Date/Publication: 2020-01-14 09:30:02 UTC
