{% set version = "2.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fma_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fma/fma_{{ version }}.tar.gz
  sha256: 69a94c3bd464176a80232d49fcd04d478d4dd59f9bf128d6a9f46e49612d27f4

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-forecast
  run:
    - r-base
    - r-forecast

test:
  commands:
    - $R -e "library('fma')"           # [not win]
    - "\"%R%\" -e \"library('fma')\""  # [win]

about:
  home: http://robjhyndman.com/software/fma/
  license: GPL (>= 2)
  summary: 'All data sets from "Forecasting: methods and applications" by Makridakis, Wheelwright
    & Hyndman (Wiley, 3rd ed., 1998).'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - philip-khor
