appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XXHDzwazOy5ukkOJMZ3gHKuoeAyCDSmGa56YDZfA4wLvTbG0bQQvSAJE4p4MMcinSieyRFpc0dlAONOACX8ut4ecLoRwQiYo28ES+bBGPi6ayZMNPnAQXpIOLv3s5kjv4KxtUV28VzkOhzMdKGKzdvODIF06g4tcrFJkmRNfrW7nyJC4fA79DOkKwu7u2TKG3AgHNDkocuesBmEwxCMzpZAv/RLkN32H6c1LuV0LU+niAp0jd4FXsI9RxkQw1ASxgkwkpSTCPhAPoknSeSgCVdoGlpN2M6iteHC+t5k5es5cVwIayZKTsplvORxk1JMAMUBiZjfs8TJCCZTyX9ziGiisw7iQ7681C7h6Muep8nx7Jt+Y/BZgF733emcnzO6N67AUKnFQvJRBDZNvVNiFqturz2CNJ6RHgbWhCeCNVkSjtZMHF8PXuspigWt86uw3uDR+2r8uY32QGGnIklnTB+X73xcdTy0PPlg7fEFE11unRoffoPGYsOg5PptJNiQvzv9v4i4O97nhGyxVLkZjfNxx6MOGw5ZIwpDsKHWcPK8dhjwaaSVrHWaLKv+yzF9LMPrKqzmmXHiDj12lP1QJ5pdKzjLMVSXuFlBCgsHxJ5FvKMoKyAjMvJZwKlLk/c/fpJ3tfmxFFxhttZd+YQ9f6rFTzwh/9R1CIPNwcqjnN74=}
